# Generated by Django 4.2.30 on 2026-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='Firebase UID of the message sender', max_length=255)),
                ('receiver_id', models.CharField(help_text='Firebase UID of the message receiver', max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation_id', models.CharField(db_index=True, help_text='Unique identifier for a conversation between two users', max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conversation_id', '-timestamp'], name='chat_messag_convers_dca7ce_idx'), models.Index(fields=['receiver_id', 'is_read'], name='chat_messag_receive_14362e_idx')],
            },
        ),
    ]
